- .github/workflows/release.yml
Fix problems with versioning in Release Action and also remove trash code.
> Fix problems in the Release Action

- functions.php
- lib/metaboxes.php
- lib/metaboxes/features.php
- lib/post-types.php
- lib/post-types/features.php
- lib/taxonomies.php
- lib/taxonomies/features-categories.php
Added support for Features post type and custom meta boxes with GraphQL
> [372] Add Support for Features Post Type and Custom Metaboxes with GraphQL

- CHANGELOG.md
- style.css
bump version to 1.0.2
**Checklist**
> feat: bump version to 1.0.2

- CHANGELOG.md
- style.css
bump theme version to v1.0.3
**Checklist**
> chore: bump theme version to 1.0.3

- lib/shortcodes.php
- lib/shortcodes/extra-faq.php
Added FAQ shortcode
**Checklist**
Close QualityUnit/web-issues#561
> [561] feat: adding extra faq shortcode

- CHANGELOG.md
- style.css
bump theme version to 1.0.4
**Checklist**
> chore: bump theme version to 1.0.4

- CHANGELOG.md
- functions.php
- style.css
bump theme version to 1.0.5
**Checklist**
> chore: bump theme version to 1.0.5

- lib/post-types.php
- lib/post-types/documentation.php
- lib/post-types/glossary.php
- lib/taxonomies.php
- lib/taxonomies/documentation-categories.php
- lib/taxonomies/features-categories.php
- lib/taxonomies/glossary-categories.php
Added post type and taxonomy for documentation and glossary
Close QualityUnit/web-issues#1450
> [1450] feat: added documentation post type

- lib/post-types/pricing-tables.php
Ability to show pricing tables post type in the GraphQL
Close QualityUnit/web-issues#1622
> [1622] fix: pricing tables

- lib/post-types.php
- lib/post-types/documentation.php
- lib/post-types/features.php
- lib/post-types/glossary.php
- lib/post-types/guide.php
- lib/taxonomies/documentation-categories.php
- lib/taxonomies/features-categories.php
- lib/taxonomies/glossary-categories.php
- templates/content-archive-features.php
- templates/content-archive.php
Post type for Guides under LPs
> [1450] feat: guide for lps post type

- lib/post-types.php
- lib/post-types/videos.php
- lib/taxonomies.php
- lib/taxonomies/videos-categories.php
**Checklist**
Close QualityUnit/web-issues#1707
> [1707] feat: videos post type and categories

- assets/styles/components/_PricingTable.scss
- assets/styles/pages/Pricing.scss
pricing table styling
Close QualityUnit/web-issues#1700
Close QualityUnit/web-issues#1662
> [1700] feat: pricing table styling

- assets/styles/common/_typography.scss
- assets/styles/components/compactHeader.scss
- assets/styles/layouts/Post.scss
- lib/post-types.php
- lib/post-types/about.php
- lib/taxonomies.php
- lib/taxonomies/about-categories.php
- templates/content-single-about.php
contact page
Close QualityUnit/web-issues#1713
> [1713] feat: contact page

- lib/shortcodes/signup-buttons.php
> fix: fixed the bug with wrong link

- templates/header.php
Close QualityUnit/web-issues#1777
> [1777] fix: download button

- assets/styles/components/_Footer.scss
pointer events on blind urls
Close QualityUnit/web-issues#1806
> [1806] fix: pointer events on blind urls

- templates/content-archive-glossary.php
variable name wrong name fix
Close QualityUnit/web-issues#1868
> [1868] fix: variable name

- templates/content-archive-glossary.php
glossary archive links fix
Close QualityUnit/web-issues#1890
> [1890] fix: glossary archive links

- assets/styles/components/_CategoryItem.scss
- lib/shortcodes/signup-buttons.php
- templates/content-archive-glossary.php
- templates/content-archive-videos.php
fixes for video styling, glossary and login/signup icons
Close QualityUnit/web-issues#1888
Close QualityUnit/web-issues#1887
Close QualityUnit/web-issues#1861
> fix: #1888, #1887, #1861,

- assets/styles/components/_CategoryItem.scss
long urls breaking layout
Close QualityUnit/web-issues#1888
> [1888] fix: long urls breaking layout

- assets/styles/elements/_Checklist.scss
- assets/styles/elements/_PostTypography.scss
- lib/widgets/improve-banner/improve-banner.php
- lib/widgets/improve-banner/layouts/banner.php
- lib/widgets/improve-banner/src/index.js
- lib/widgets/improve-banner/src/layouts/frontend/ImproveBanner.jsx
- lib/widgets/improve-banner/src/scss/editor.scss
editable improve banner, check icons in lists
Close QualityUnit/web-issues#1897
Close QualityUnit/web-issues#1903
> [1903] feat: editable improve banner, check icons in lists

- assets/styles/elements/_Checklist.scss
- lib/widgets/improve-banner/src/scss/style.scss
[Describe what was changed in the Pull Request](fix: checklists and styling of improve banner in guttenberg)
Close QualityUnit/web-issues#1897
Close QualityUnit/web-issues#1903
> fix: checklists and styling of improve banner in guttenberg

- assets/scripts/app/videoTranscript.js
- assets/styles/Elementor.scss
- assets/styles/app.scss
- assets/styles/components/_SimilarSources.scss
- assets/styles/shortcodes/VideoTranscript.scss
- lib/widgets/whatblock/src/scss/editor.scss
- lib/widgets/whatblock/src/scss/style.scss
- templates/content-page.php
- templates/content-single-features.php
- templates/content-single-glossary.php
- templates/content-single-videos.php
- templates/content-single.php
Close QualityUnit/web-issues#1900
Close QualityUnit/web-issues#1944
Close QualityUnit/web-issues#1954
> fix: #1900, #1944, #1954

- assets/styles/common/_typography.scss
- assets/styles/elements/_PostTypography.scss
**Checklist**
Close QualityUnit/web-issues#[ISSUE_NUMBER]
> fix: small visual fixes

- assets/styles/common/_global.scss
- assets/styles/components/_DocumentationSidebar.scss
- assets/styles/components/compactHeader.scss
- assets/styles/layouts/Documentation.scss
- lib/custom-blocks/compact-header.php
- lib/helpers.php
- lib/post-types/documentation.php
- templates/content-archive-features.php
- templates/content-archive-glossary.php
- templates/content-archive-videos.php
- templates/content-single-about.php
- templates/content-single-documentation.php
- templates/content-single-features.php
- templates/content-single-glossary.php
- templates/content-single-videos.php
- templates/content-single.php
- templates/documentation-search.php
- templates/footer.php
- templates/header.php
Initial implementation of Documentation in php.
ToDo – sidebar for top categories and redirects
> [1708] documentation

- assets/scripts/vendor/splide.js
- assets/styles/common/_mixins.scss
- assets/styles/common/_variables.scss
- assets/styles/common/splide.scss
- assets/styles/components/SliderCutted.scss
- assets/styles/components/_AuthorCard.scss
- assets/styles/components/_BlogPostHeader.scss
- assets/styles/components/_BlogShare.scss
- assets/styles/components/_BlogShareSidebar.scss
- assets/styles/components/_SignupForm-sidebar.scss
- assets/styles/elements/_PostTypography.scss
- assets/styles/elements/_Typography.scss
- assets/styles/layouts/Archive.scss
- assets/styles/layouts/_Blog.scss
- assets/styles/layouts/_BlogPost.scss
- assets/styles/layouts/_PostHeader-narrow.scss
- assets/styles/layouts/_Post__header-images.scss
- assets/styles/pages/blog.scss
- assets/styles/pages/post.scss
- lib/assets.php
- lib/pagesources.php
- lib/shortcodes/signup-sidebar.php
- template-blog-header.php
- template-blog.php
- templates/content-archive.php
- templates/content-single.php
Added styles for blog archive and posts
Close QualityUnit/web-issues#2253
> [2253] feat: blog styles

- assets/styles/app.scss
- assets/styles/common/splide.scss
- assets/styles/components/_BlogShare.scss
- assets/styles/components/_BlogShareSidebar.scss
- assets/styles/elements/_Breadcrumb.scss
- assets/styles/elements/_PostTag.scss
- assets/styles/elements/_Typography.scss
- assets/styles/layouts/_BlogPost.scss
small bugfixes to blog styles
Close QualityUnit/web-issues#2253
> [2253] fix: small bugfixes to blog styles

- assets/scripts/app/app.js
- assets/styles/common/_animations.scss
- assets/styles/common/_variables.scss
- assets/styles/components/_Header.scss
- assets/styles/elements/Header/_HeaderNavigationMain.scss
- assets/styles/elements/Header/_HeaderNavigationSubItemsColors.scss
- assets/styles/elements/Header/_HeaderNavigationSubMenu.scss
- templates/header.php
Redesign desktop and mobile menu. Rewrited JS, SASS, PHP
**Checklist**
Close QualityUnit/web-issues#2120
> [2120] Redesign of the URLsLab main menu

- assets/styles/elements/Header/_HeaderNavigationSubItemsColors.scss
- assets/styles/elements/Header/_HeaderNavigationSubMenu.scss
I fixed the broken menu in firefox and limited the description of menu items to a maximum of 2 lines
**Checklist**
Close QualityUnit/web-issues#2409
> [2409] Broken style urlslab menu

- lib/shortcodes/signup-sidebar.php
- template-blog.php
- templates/content-single-glossary.php
> feat: partially disable grafana

- assets/scripts/app/app.js
deleted script which adding target blank to links
**Checklist**
Close QualityUnit/web-issues#2421
> [2421] deleted script which adding target blank to links

- assets/styles/Elementor.scss
- assets/styles/common/_typography.scss
- assets/styles/components/_BlockBackground.scss
- assets/styles/components/_BlockBasic.scss
- assets/styles/components/_BlockImage.scss
- assets/styles/components/_HeroBanner.scss
- assets/styles/layouts/Elementor.scss
- assets/styles/vendor/_elementor-cherrypicks.scss
- assets/styles/vendor/_elementor-typography.scss
- composer.lock
- templates/content-page.php
I edited new sections on homepage and I edited some styles for mobile devices.
**Checklist**
Close QualityUnit/web-issues#2410
> [2410] Urlslab - create new content KW

- assets/styles/components/_BlockImage.scss
I added some styles for play button
**Checklist**
Close QualityUnit/web-issues#2410
> [2410] Fixed some styles for sections

- assets/styles/elements/Header/_HeaderNavigationMain.scss
- assets/styles/elements/Header/_HeaderNavigationSubMenu.scss
- templates/header.php
I changed styles for mobile menu
**Checklist**
Close QualityUnit/web-issues#2471
> [2471] change of mobile menu design

- assets/styles/components/_BlockCaseStudy.scss
i fixed styles for check marks in case study element on the pricing page.
**Checklist**
Close QualityUnit/web-issues#2538
> [2538] The Elementor list element is not working proeprly in URLsLab Web

- lib/functions.php
- lib/functions/redirects.php
I added redirects for Urlslab categories
**Checklist**
Close QualityUnit/web-issues#2531
> [2531] Added redirects for Urlslab categories

- assets/styles/elements/_Button.scss
svg margin 
Close QualityUnit/web-issues#2707
> [2707] fix: svg margin

- assets/scripts/app/responsiveTable.js
> [2791] info table icon fix

- assets/styles/components/_Login.scss
- assets/styles/elements/Header/_HeaderNavigationMain.scss
> fix: login

- templates/header.php
hiding get plugin button from menu
> fix: commenting out get plugin btn

- assets/scripts/app/responsiveTable.js
- assets/styles/components/_Form.scss
- templates/header.php
> feat: demoform styling

- .github/workflows/build-test.yml
- .github/workflows/eslint.yml
- .github/workflows/stylelint.yml
- lib/widgets/improve-banner/package.json
- lib/widgets/improve-banner/yarn.lock
- lib/widgets/whatblock/package.json
- lib/widgets/whatblock/yarn.lock
- package.json
- yarn.lock
upgrading to node 20
Close QualityUnit/web-issues#2863
> [2863] feat: upgrading to node 20

- .github/workflows/publish-release.yml
**Checklist**
Close QualityUnit/web-issues#2863
> [2863] fix. node build to 20

- assets/styles/components/Table.scss
- lib/functions/component-imports.php
**Checklist**
Close QualityUnit/web-issues#[ISSUE_NUMBER]
> fix: loading assets only in edit post mode

- assets/styles/Elementor.scss
- assets/styles/app.scss
- assets/styles/common/_gridLayout.scss
- assets/styles/elements/Header/_HeaderNavigationMain.scss
- assets/styles/elements/Header/_HeaderNavigationSubItemsColors.scss
- assets/styles/elements/Header/_HeaderNavigationSubMenu.scss
- composer.lock
feat: menu redesign
Close QualityUnit/web-issues#2904
> feat: menu redesign

- assets/styles/Elementor.scss
- templates/head.php
> fix: header

- templates/content-single-features.php
Added excerpt to compact header for features single page
**Checklist**
> Adding excerpt for features posts

- assets/scripts/custom/responsiveTable.js
- assets/styles/common/_variables.scss
- assets/styles/components/SidebarTOC.scss
- assets/styles/components/Table.scss
- assets/styles/components/_BlockCaseStudy.scss
- assets/styles/components/_BlogShareSidebar.scss
- assets/styles/components/_PricingPrograms.scss
- assets/styles/components/_PricingTable.scss
- assets/styles/components/_SignupForm-sidebar.scss
- assets/styles/components/compactHeader.scss
- assets/styles/elements/Header/_HeaderNavigationMain.scss
- assets/styles/elements/Header/_HeaderNavigationSubMenu.scss
- assets/styles/elements/_Button.scss
- assets/styles/layouts/Header.scss
- assets/styles/pages/Pricing.scss
pricing redesign
Close QualityUnit/web-issues#2947
> [2947] feat: pricing redesign

- assets/scripts/app/tooltips.js
- assets/scripts/custom/responsiveTable.js
- assets/scripts/vendor/popper.js
- assets/styles/Elementor.scss
- assets/styles/app.scss
- assets/styles/components/Table.scss
- assets/styles/elements/_Tooltip.scss
- assets/styles/layouts/Post.scss
- gulpfile.js
- lib/assets.php
- page.php
Table tooltip fix
Close https://github.com/QualityUnit/web-issues/issues/2954
> Table tooltip fix

- lib/functions/redirects.php
i added function for redirect glossary categories
**Checklist**
Close QualityUnit/web-issues#2945
> [2945] Make glossary categories invisible

- assets/styles/components/Table.scss
- assets/styles/components/_BlockCaseStudy.scss
- assets/styles/components/_PricingPrograms.scss
- assets/styles/components/_PricingTable.scss
- assets/styles/layouts/Footer.scss
Close QualityUnit/web-issues#2955
Close QualityUnit/web-issues#2956
> [2955] fix: pricing tables, footer

- page.php
Close QualityUnit/web-issues#2954
> [2954] fix: removing time for text plain pages (terms etc)

- assets/styles/elements/_Typography.scss
- composer.lock
added tag for elementor hero titles
Close QualityUnit/web-issues#2962
> [2962] feat: added tag for elementor hero titles

- lib/shortcodes/sidebar-banner.php
fix order of condition for sidebar banner text in button
> fix: condition order

- assets/styles/components/_PricingPrograms.scss
pricing fix
Close QualityUnit/web-issues#2963
> [2963] fix: pricing

- assets/styles/components/_PricingPrograms.scss
- assets/styles/components/_PricingTable.scss
Fixing pricing issues 
Close QualityUnit/web-issues#2972
> [2972] fix: pricing

- assets/styles/common/_global.scss
- assets/styles/components/_HeroBanner.scss
- assets/styles/components/_PricingPrograms.scss
- assets/styles/layouts/_Posts.scss
- lib/widgets/improve-banner/improve-banner.php
- templates/content-archive-glossary.php
- templates/head.php
improving cls and lcp
Close QualityUnit/web-issues#2976
> [2976] feat: improving cls and lcp

- base-scripts.php
grafana scripts added, new fh chatbot
Close QualityUnit/web-issues#3078
> [3078] fix: grafana scripts added, new fh chatbot

- assets/styles/elements/_PostTypography.scss
I rewrote the styles for the lists because after updating gutenberg the list has a new class
**Checklist**
Close QualityUnit/web-issues#3088
> [3088 ] Lists not working on all webs

- assets/scripts/custom/filter.js
- assets/styles/layouts/_Posts.scss
- lib/custom-blocks/compact-header.php
I edited JS file for search in the custom post types. Added function for cancel submit search form after press enter key. Edited php code for post types. Tested in the all search forms in header
**Checklist**
Close QualityUnit/web-issues#3196
> [3196] Search in template page redirect incorrectly

- .github/workflows/add_to_project.yml
Added back action for add to project because don't have more workflows in our account 5 its maximum
> Added action for add to project
